### ISSUE TITLE
Evaluate relative paths to make them match changed paths

### ISSUE THREAD

**Issue by stoesselt** [tomasbjerre/violations-lib#40]
I have a GCC warning. However, the compiler warning is not shown/commented in the PR.

I also use the warnings plugin to create a Jenkins internal report. I use both plugins with the same output files of GCC, and in the warnings plugin it is identified and resolved correctly. So the path in total is correct.

In contrast to the other output logs I use, I know that this has relative parts in its path, e.g. /foo/bar/../foobar.cpp. I don't know if Bitbucket can handle such a path, does the plugin resolve it before invoking the url?

**Comment by tomasbjerre** [comment]
Relative parts is most likely the problem. Can you not get rid of that?

Den mån 10 sep. 2018 14:41stoesselt <notifications@github.com> skrev:

**Comment by stoesselt** [comment]
I have to say it, I love your response times ^^

Ok, I got rid of the relative path parts and it works now. In other words Bitbucket cannot cope with the relative path parts. 

I would like to have this issue as an enhancement. Though it only seems relevant to Bitbucket I would keep it at the lowest level and do proper path resolution before providing it to higher layers..

**Comment by tomasbjerre** [comment]
Thanks.

What happens here is that the Bitbucket APi returns paths that were changed in the PR. Like `/this/path/was/changed.txt` and in the report file we have maby `/this/path/was/not/../changed.txt`. And the file will only be commented if [they are equal](https://github.com/tomasbjerre/violation-comments-to-bitbucket-server-lib/blob/master/src/main/java/se/bjurr/violations/comments/bitbucketserver/lib/BitbucketServerCommentsProvider.java#L163).

This can definitely be fixed in the plugin or one of its supporting libraries. I think this lib should be responsible for just parsing the report files and making its content available.

I think, maby, this issue should be resolved with a change in [violation-comments-lib](https://github.com/tomasbjerre/violation-comments-lib).

**Comment by tomasbjerre** [comment]
I think this was fixed when fixing https://github.com/tomasbjerre/violations-command-line/issues/7
