### ISSUE TITLE
[flake8] file names with prefix `./` are not detected

### ISSUE THREAD

**Issue by uhafner** [tomasbjerre/violations-lib#58]
See https://github.com/jenkinsci/analysis-model/commit/881b1cf1c365817e2bd571bc35d6e9095932aadc

**Comment by pabepadu** [comment]
I had a look in the parser:
`violations-lib/src/main/java/se/bjurr/violations/lib/parsers/Flake8Parser.java`

I think it's not due to the `./` but the column part, the pattern matching accept only 1 decimal:
`"([^:]*):(\\d+)?:?(\\d)?:? \\[?(\\D+)(\\d*)\\]? (.*)"`
and it should be with a `+`, like this:
`"([^:]*):(\\d+)?:?(\\d+)?:? \\[?(\\D+)(\\d*)\\]? (.*)"`

**Comment by tomasbjerre** [comment]
You are right @pabepadu !

Released a fix as 1.81 now!
