### ISSUE TITLE
JSHint parser uses JSLint format

### ISSUE THREAD

**Issue by AaronAsAChimp** [tomasbjerre/violations-lib#74]
The JSHint parser does not parse the JSHint format. Instead it parses the JS***L***int format. While workable with the `--reporter=jslint` flag, it was confusing and impossible to determine without reading the source code.

The JSHint parser should be renamed to be the JSLint parser. The JSHint format is below for comparison:

```
stage\ppjs\webapps\idashboards\js\modules\admin\pagehandlers\alerts\smscarriers.js: line 164, col 39, Missing semicolon.

1 error
```

With verbose flag set:
```
stage\ppjs\webapps\idashboards\js\modules\admin\pagehandlers\alerts\smscarriers.js: line 164, col 39, Missing semicolon. (W033)

1 error
```

**Comment by tomasbjerre** [comment]
Thanks for reporting! Made a release with that change.

It will break backwards compatibility once released in whatever tool you are using the library with. So you may want to use the `--reporter=checkstyle` and use the `CHECKSTYLE` parser instead. So that you don't need to change it when this fix is later built into the tool you use.

**Comment by tomasbjerre** [comment]
All tools that I maintain should now have this fix in their latest release.
